name: Build and Push Images to Docker Hub

on:
    push:
        branches:
            - master

jobs:
    build_and_push_php-81-laravel-dev_image:
        name: Build and Push php-81-laravel-dev Image
        runs-on: ubuntu-20.04
        timeout-minutes: 10
        steps:
            -   name: Checkout Repo
                uses: actions/checkout@v2

            -   name: Login to Docker Hub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            -   name: Build image
                env:
                    DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
                run: docker build --progress plain --pull --no-cache --tag "$DOCKERHUB_USERNAME/php-81-laravel-dev:latest" "php-81-laravel-dev"

            -   name: Push image to Docker Hub
                env:
                    DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
                run: docker push "$DOCKERHUB_USERNAME/php-81-laravel-dev:latest"

    build_and_push_php-8-laravel-dev_image:
        name: Build and Push php-8-laravel-dev Image
        runs-on: ubuntu-20.04
        timeout-minutes: 10
        steps:
            -   name: Checkout Repo
                uses: actions/checkout@v2

            -   name: Login to Docker Hub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            -   name: Build image
                env:
                    DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
                run: docker build --progress plain --pull --no-cache --tag "$DOCKERHUB_USERNAME/php-8-laravel-dev:latest" "php-8-laravel-dev"

            -   name: Push image to Docker Hub
                env:
                    DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
                run: docker push "$DOCKERHUB_USERNAME/php-8-laravel-dev:latest"

    build_and_push_php-74-laravel-dev_image:
        name: Build and Push php-74-laravel-dev Image
        runs-on: ubuntu-20.04
        timeout-minutes: 10
        steps:
            -   name: Checkout Repo
                uses: actions/checkout@v2

            -   name: Login to Docker Hub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            -   name: Build image
                env:
                    DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
                run: docker build --progress plain --pull --no-cache --tag "$DOCKERHUB_USERNAME/php-74-laravel-dev:latest" "php-74-laravel-dev"

            -   name: Push image to Docker Hub
                env:
                    DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
                run: docker push "$DOCKERHUB_USERNAME/php-74-laravel-dev:latest"
