name: Update Images

on:
    push:
        paths:
            - 'php-8-laravel-dev/Dockerfile'
            - 'php-74-laravel-dev/Dockerfile'

jobs:
    build_and_push:
        name: build and push
        runs-on: ubuntu-20.04
        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -   name: Login to Docker Hub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            -   name: Build images and Push it to Docker Hub
                run: |
                    CHANGED_FILES="$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }})"

                    if [[ $CHANGED_FILES == *"php-8-laravel-dev/Dockerfile"* ]]; then
                        docker build --no-cache -t "devmoath/php-8-laravel-dev:latest" "php-8-laravel-dev"
                        docker push "devmoath/php-8-laravel-dev:latest"
                    fi

                    if [[ $CHANGED_FILES == *"php-74-laravel-dev/Dockerfile"* ]]; then
                        docker build --no-cache -t "devmoath/php-74-laravel-dev:latest" "php-74-laravel-dev"
                        docker push "devmoath/php-74-laravel-dev:latest"
                    fi
